version = "0.0.1" # version: Option<String>
# entrypoint = "lorem()" # entrypoint: Option<String>

[wasi]
version = "preview_2" # version: Option<bool>
# tls, nn, threads, http, tcp, udp, inherit_env, nn, http, ...: Option<bool>
# TODO nn-graph

[mount]
"." = "/"
# "relative/path" = "/path/in/runtime"
# "/absolute/path/to/file" = "/another/path/in/runtime"
